### PR TITLE
Fix typo to link resources

### LINKED ISSUE #2310: gmake2 not work with file.rc
[Moltiplicazione.zip](https://github.com/user-attachments/files/17534161/Moltiplicazione.zip)
windows 10
mingw64 v.11
premake5 v.5.00-beta 2

Hello,
premake5 compiles perfectly with the gmake option, but with gmake2 it ignores the file.rc

Carlo Sala

### PR DESCRIPTION
**Pull request by Jarod42**
**What does this PR do?**

Fix typo in gmake2 generator about resource

**How does this PR change Premake's behavior?**

Allow to link resource with gmake2

**Anything else we should know?**

closes #2310 

**Did you check all the boxes?**

- [x] Focus on a single fix or feature; remove any unrelated formatting or code changes
- [x] Add unit tests showing fix or feature works; all tests pass
- [x] Mention any [related issues](https://github.com/premake/premake-core/issues) (put `closes #XXXX` in comment to auto-close issue when PR is merged)
- [x] Follow our [coding conventions](https://github.com/premake/premake-core/blob/master/CONTRIBUTING.md#coding-conventions)
- [x] Minimize the number of commits
- [ ] Align [documentation](https://github.com/premake/premake-core/tree/master/website) to your changes

### CODE REVIEW

File: modules/gmake2/tests/test_gmake2_objects.lua [hunk 1]
```diff
@@ -50,6 +50,22 @@ OBJECTS += $(OBJDIR)/hello.o
 		]]
 	end
 
+	function suite.listResoucesInProjectObjects()
+		files { "src/hello.rc" }
```
Comment (nickclark2016) [inline modules/gmake2/tests/test_gmake2_objects.lua:54]: Should this be res, not rc?

Comment (Jarod42) [reply modules/gmake2/tests/test_gmake2_objects.lua:54]: .rc creates .res

**Review by nickclark2016 — APPROVED** [review]
