### PR TITLE
Fix MinGW builds of Premake

### LINKED ISSUE #559: Curl error with MinGW building
I can't build premake 5 with mingw because of error:

``` c
==== Building curl-lib (release) ====
connect.c
In file included from ../../contrib/curl/lib/connect.c:65:0:
../../contrib/curl/lib/select.h:82:29: error: array type has incomplete element type 'struct pollfd'
 int Curl_poll(struct pollfd ufds[], unsigned int nfds, int timeout_ms);
                             ^
make[1]: *** [curl-lib.make:259: obj/Release/curl-lib/connect.o] Ошибка 1
make: *** [Makefile:63: curl-lib] Ошибка 2
```

I use `gmake.windows` to build.

### PR DESCRIPTION
**Pull request by starkos**
**What does this PR do?**

Gets Premake's bootstrap makefile to work properly with MinGW (64-bit only). This is an attempt to resurrect PR #1111.

Closes #559.

```sh
# To build with bootstrap script
set CC=gcc
mingw32-make -f Bootstrap.mak mingw PLATFORM=x64

# To build with Premake
premake5 --cc=mingw gmake2
mingw32-make config=debug_x64
```

**How does this PR change Premake's behavior?**

A few additions were made to Premake to improve support for MinGW specifically. Those were added by @tdesveauxPKFX in #1111, I've maintained them as is.

**Anything else we should know?**

I've successfully built Premake using the 64-bit version of MinGW using these changes. I was not able to build with the 32-bit version, though that may have  been a local setup issue; I didn't pursue it. Since, best I could tell, we aren't currently able to build with MinGW at all this seems like an incremental win.

I left @tdesveauxPKFX's commits intact so he would get some credit for the fix, since he did the bulk of the work on this one.

Two unit tests fail with the MinGW build:

1. `base_os.remove_ReturnsTrue_OnFile` gets an "Access denied" error when it tries to delete a temporary file
2. `premake_binmodules.testExample` fails with "module 'example' not found"

**Did you check all the boxes?**

- [x] Focus on a single fix or feature; remove any unrelated formatting or code changes
- [ ] ~~Add unit tests showing fix or feature works; all tests pass~~ _(minimal code changes)_
- [x] ~~Mention any [related issues](https://github.com/premake/premake-core/issues)~~ 
- [ ] Follow our [coding conventions](https://github.com/premake/premake-core/blob/master/CONTRIBUTING.md#coding-conventions)
- [x] Minimize the number of commits

*You can now [support Premake on our OpenCollective](https://opencollective.com/premake). Your contributions help us spend more time responding to requests like these!*

### CODE REVIEW

File: premake5.lua [hunk 1]
```diff
@@ -168,7 +172,10 @@
 			targetdir   "bin/release"
 
 		filter "system:windows"
-			links       { "ole32", "ws2_32", "advapi32" }
+			links       { "ole32", "ws2_32", "advapi32", "version" }
```
Comment (samsinsane) [inline premake5.lua]: Is version needed on non-MinGW Windows builds too?

File: src/tools/mingw.lua [hunk 2]
```diff
@@ -0,0 +1,8 @@
+--
+-- mingw.lua
+-- MinGW toolset adapter for Premake
+-- Copyright (c) 2018 Jason Perkins and the Premake project
```
Comment (samsinsane) [inline src/tools/mingw.lua]: Might be worth rolling this over to 2020.

**Comment by starkos** [comment]
Rebased to master, waiting for checks to complete.
