### PR TITLE
Fix #1795: project generation fails with "Error: attempt to index a function value"

### LINKED ISSUE #1795: project generation fails with "Error: attempt to index a function value"
**What seems to be the problem?**
Premake5 raises an error during any project generation:
```
Building configurations...
Error: attempt to index a function value
stack traceback:
        [string "src/base/api.lua"]:309: in field 'checkValue'
        [string "src/base/oven.lua"]:255: in local 'base'
        (...tail calls...)
        [string "src/base/oven.lua"]:197: in field 'bakeConfigs'
        [string "src/base/oven.lua"]:44: in field 'bake'
        [string "src/base/container.lua"]:61: in field 'bake'
        [string "src/base/container.lua"]:69: in field 'bakeChildren'
        [string "src/base/global.lua"]:8: in field 'bake'
        [string "src/base/container.lua"]:61: in field 'bake'
        [string "src/base/oven.lua"]:12: in field 'bake'
        [string "src/_premake_main.lua"]:163: in field '?'
        [string "src/base/_foundation.lua"]:62: in function 'premake.callArray'
        [string "src/_premake_main.lua"]:225: in function '_premake_main'
```

**What version of Premake are you using?**
premake 5.0-alpha16

**Anything else we should know?**
Digging into the code, I've noticed that in the file `api.lua`, a `function` type is passed to `ipairs()` which is not allowed:
```lua
-- api.lua, line 661

if not canonical then
    for _, allow in ipairs(field.allowed)       <---------- here
        do
            if type(allow) == "function" then
            ...
```

I did a small patch myself, I'll create a PR that should fix this.

### PR DESCRIPTION
**Pull request by somyungoh**
**What does this PR do?**

Only allow "table" type to be passed into `ipairs()` in the code `api.lua`, line `661`.
Closes #1795.

**How does this PR change Premake's behavior?**

No premake behavioral change, but prevents error when invalid type being passed to `ipairs()`.

**Anything else we should know?**

No.

**Did you check all the boxes?**

- [x] Focus on a single fix or feature; remove any unrelated formatting or code changes
- [x] Add unit tests showing fix or feature works; all tests pass
- [x] Mention any [related issues](https://github.com/premake/premake-core/issues) (put `closes #XXXX` in comment to auto-close issue when PR is merged)
- [x] Follow our [coding conventions](https://github.com/premake/premake-core/blob/master/CONTRIBUTING.md#coding-conventions)
- [x] Minimize the number of commits
- [ ] Align [documentation](https://github.com/premake/premake-core/tree/master/website) to your changes

*You can now [support Premake on our OpenCollective](https://opencollective.com/premake). Your contributions help us spend more time responding to requests like these!*

### CODE REVIEW

File: src/base/api.lua [hunk 1]
```diff
@@ -658,7 +658,7 @@
 		-- If a tool was not found, check to see if there is a function in the
 		-- table to check against.  For each function in the table, check if
 		-- the value is allowed (break early if so).
-		if not canonical then
+		if not canonical and type(field.allowed) == "table" then
```
Comment (nickclark2016) [inline src/base/api.lua:661]: I think this is the correct change, but I'm wondering if we should output a warning if it's not the expected type?

**Review by nickclark2016 — APPROVED** [review]

**Comment by nickclark2016** [comment]
Apologies on such a long follow up time. If you don't mine, can you rebase your branch off the most recent master, then I'll go ahead and merge? I'm happy with these changes.
