### PR TITLE
Fixes filters using an aliased value

### LINKED ISSUE #2614: `filter` no longer matches `architecture:arm64`, starting in beta8
**What seems to be the problem?**
`targetsuffix` is no longer respected for ARM64, starting in beta8.
It was working fine for me in beta2 through beta7.
I've been using premake for ARM64 on Windows for years (cross-compiling and publishing generated ARM64 builds).

**What did you expect to happen?**
The `<TargetName>` should include the `targetsuffix`, but for ARM64 it no longer does.
I expected ARM64 to respect the `targetsuffix` as it did in beta2 through beta7.
In beta8 x86 and x64 include the suffix, but ARM64 does not.

**What have you tried so far?**
1. I bisected which version of premake introduced this problem:  beta2 through beta7 respect `targetsuffix` for ARM64, but beta8 does not -- the regression was introduced in beta8.
2. I'm working on finding a way to work around this beta8 regression.
3. I may also track down what commit introduced the regression, after I find a workaround (or give up on finding a workaround).

**How can we reproduce this?**
Use the following premake5.lua file, run `premake5 vs2022`, and then observe the `<TargetName>` fields in the resulting `repro.vcxproj` file.
```lua
workspace("repro")
    configurations({"debug", "release", "final"})
    platforms({"x86", "x64", "arm64"})

project("repro")
    kind("consoleapp")

    filter {cfg, "architecture:x86"}
        targetsuffix("_x86")

    filter {cfg, "architecture:x64"}
        targetsuffix("_x64")

    filter {cfg, "architecture:arm64"}
        targetsuffix("_arm64")
```

- [x] Visual Studio 2022 (vs2022)
- [ ] I haven't tried any other versions of VS yet, but since VS is not even being invoked it seems unlikely to be related to the VS version.

**What version of Premake are you using?**
```console
> premake5 --version
premake5 (Premake Build Script Generator) 5.0.0-beta8
```

### PR DESCRIPTION
**Pull request by nickclark2016**
**What does this PR do?**

Fixes #2614

**How does this PR change Premake's behavior?**

No

**Anything else we should know?**

N/A

**Did you check all the boxes?**

- [x] Focus on a single fix or feature; remove any unrelated formatting or code changes
- [x] Add unit tests showing fix or feature works; all tests pass
- [x] Mention any [related issues](https://github.com/premake/premake-core/issues) (put `closes #XXXX` in comment to auto-close issue when PR is merged)
- [x] Follow our [coding conventions](https://github.com/premake/premake-core/blob/master/CONTRIBUTING.md#coding-conventions)
- [x] Minimize the number of commits
- [x] Align [documentation](https://github.com/premake/premake-core/tree/master/website) to your changes

*You can now [support Premake on our OpenCollective](https://opencollective.com/premake). Your contributions help us spend more time responding to requests like these!*

### CODE REVIEW

File: modules/vstudio/tests/vc2010/test_target_name.lua [hunk 1]
```diff
@@ -0,0 +1,128 @@
...
+
+
+--
+-- Target name with targetsuffix with ARM64 architecture
+--
+
+    function suite.targetWithArm64FilterSuffix()
+        architecture "ARM64"
+
+        filter { "architecture:ARM64" } -- Should match when architecture is AARCH64
```
Comment (chrisant996) [inline modules/vstudio/tests/vc2010/test_target_name.lua:75]: Would it be worth adding a lowercase test?

Comment (chrisant996) [reply modules/vstudio/tests/vc2010/test_target_name.lua:75]: Or better yet, a mixed case test, e.g. `aRm64`.

File: modules/vstudio/vstudio.lua [hunk 2]
```diff
@@ -34,6 +34,10 @@
 	vstudio.vs2010_architectures =
 	{
 		win32   = "x86",
+		x86       = "x86",
+		x86_64    = "x64",
+		ARM       = "ARM",
+		AARCH64   = "ARM64",
 	}
```
Comment (Jarod42) [inline modules/vstudio/vstudio.lua:41]: It is now identical to `vs200x_architectures`.
It seems they can be regrouped, and so below function might be simplified.

File: src/base/context.lua [hunk 3]
```diff
@@ -100,9 +100,25 @@
...
 		elseif value ~= nil then
 			value = tostring(value):lower()
+
+			local field = p.field.get(key)
+			if field and field.aliases then
+				local aliased = field.aliases[value]
+				if aliased then
+					value = tostring(aliased):lower()
+				end
+			end
```
Comment (Jarod42) [inline src/base/context.lua]: That pattern is repeated 3 times, maybe create a subfunction, something like:
```lua
function p.field.alias_resolved(key, value) do
  value = value:lower()
  local field = p.field.get(key)
  if field and field.aliases then
    local aliased = field.aliases[value]
	if aliased then
		value = tostring(aliased):lower()
	end
  end 
  return value
end
```

Comment (nickclark2016) [reply src/base/context.lua]: These aren't quite the same. One is iterating over a table, one is a single value.

File: modules/vstudio/vstudio.lua (hunk 2 above)
Comment (nickclark2016) [reply modules/vstudio/vstudio.lua:41]: Keeping is separate in case any plugins are relying on this.

File: modules/vstudio/tests/vc2010/test_target_name.lua (hunk 1 above)
Comment (nickclark2016) [reply modules/vstudio/tests/vc2010/test_target_name.lua:75]: We probably should, but that sort of test would be better fit elsewhere in the filter logic, not the VS logic.

File: src/base/context.lua (hunk 3 above)
Comment (chrisant996) [reply src/base/context.lua]: The pattern is identical in all three places, and can be factored to call the function Jarod42 suggested.

Here is what the 3 call sites would become:
_(Edit 1: fixed `.` to `:` for calling the function.)_
_(Edit 2: oops, Jarod42 already handled the missing `:lower()` issue in criteria.lua and factored further than I had initially noticed, and I've updated the call sites below accordingly.)_

**context.lua**
```lua
if type(value) == "table" then
	for i = 1, #value do
		value[i] = p.field:alias_resolved(key, value[i])
	end
elseif value ~= nil then
	value = p.field:alias_resolved(key, value)
end
```

**criteria.lua**
```lua
if prefix then
	word[1] = p.field:alias_resolved(prefix, word[1])
end
```

Comment (nickclark2016) [reply src/base/context.lua]: Ah, misunderstood the comment

Comment (chrisant996) [reply src/base/context.lua]: LGTM!  (and you're right, my `.` was right the first time, not `:`)

**Review by Jarod42 — APPROVED** [review]
