### PR TITLE
Fixed issue with the OBJDIR value not being escaped

### LINKED ISSUE #705: generate gmake file for mingw error.
hi, it's me again.
I write a premake for AkelPad's language resource.
project name has space like this```Chinese (Simplified)```
premake generate name ```Chinese (Simplified).make``` for gmake.
but do make, error appear!
filelist:
```
Belorussian.make
Brazilian.make
Catalan.make
Chinese (Simplified).make
Chinese (Traditional).make
Czech.make
Dutch.make
English.make
Finnish.make
French.make
German.make
Greek.make
Hungarian.make
Italian.make
Japanese.make
Korean.make
Makefile
Polish.make
Romanian.make
Russian.make
Slovak.make
Spanish.make
Ukrainian.make
Uzbek.make
```
I don't know is space's problem or bracket's problem.

I upload the whole solution to Github
https://github.com/leeonix/AkelPad

```
premake5 --file languages.lua gmake
```

appear this gmake problem.

and issue #704 using
```
premake5 --file plugins.lua gmake
```
can reappear

and 

using vs2015 vs2017 param, it's fine.

@starkos 
@tvandijck

### PR DESCRIPTION
**Pull request by samsinsane**
Resolves #705

### CODE REVIEW

File: src/actions/make/_make.lua [hunk 1]
```diff
@@ -232,7 +232,7 @@
 ---------------------------------------------------------------------------
 
 	function make.objdir(cfg)
-		_x('  OBJDIR = %s', project.getrelative(cfg.project, cfg.objdir))
+		_x('  OBJDIR = %s', premake.esc(project.getrelative(cfg.project, cfg.objdir)))
```
Comment (tvandijck) [inline src/actions/make/_make.lua]: could use p.esc, but that's nitpicking....

Comment (samsinsane) [inline src/actions/make/_make.lua]: This file seems to mix and match `premake.` and `p.`, I was basing my usage off something else, which turns out is in another file entirely, woops! I might create a PR tomorrow that replaces *all* (within reason) occurrences of `premake.` with `p.`, for consistency.

Comment (tvandijck) [inline src/actions/make/_make.lua]: works for me ;)
