### PR TITLE
Strip linking decorators for sibling projects

### LINKED ISSUE #1685: Links with `:static` suffix do not generate correct target dependencies
**What seems to be the problem?**
Given this sample project where `links` is used with `:static` suffix to enable putting the static library in static section of link libraries (`-Wl,-Bstatic`):
```lua
workspace "MyWorkspace"
    configurations { "Debug" }
    toolset "gcc"

    project "MyLib"
        kind "StaticLib"
        files { "lib.cpp" }

    project "MyApp"
        kind "ConsoleApp"
        libdirs { "bin/Debug" }
        links { "MyLib:static" }
        files { "app.cpp" }
```
When premake is called to generate gmake Makefiles, and make is invoked to build MyApp:
```
$ premake5 gmake
$ make MyApp
```

Then it fails to build with the compiler not finding the MyLib:
```
==== Building MyApp (debug) ====
Creating obj/Debug/MyApp
app.cpp
Creating bin/Debug
Linking MyApp
/usr/bin/ld: cannot find -lMyLib
collect2: error: ld returned 1 exit status
make[1]: *** [MyApp.make:54: bin/Debug/MyApp] Error 1
make: *** [Makefile:31: MyApp] Error 2
```

This is because MyApp in generated Makefiles does not include a dependency on MyLib target. Therefore, MyLib is never built and the linking phase of MyApp fails.

**What did you expect to happen?**
Generated Makefiles should contain the correct dependency of MyApp on MyLib and `make MyApp` should build first MyLib, then MyApp successfully.

**What have you tried so far?**
The only workaround is to manually build MyLib first, then MyApp.

**How can we reproduce this?**
Run the example given above.

**What version of Premake are you using?**
premake5 (Premake Build Script Generator) 5.0.0-alpha16

**Anything else we should know?**
When not using the `:static` suffix, the dependencies are correct and the build works as expected:

However, that is not a valid workaround for the project I am working on. In this particular case, putting the library in `-Wl,-Bstatic` section is quite important for building the project correctly.

### PR DESCRIPTION
**Pull request by samsinsane**
- Added unit tests for linking decorators

**What does this PR do?**

Fixes #1685 by ignoring the linking decorators for sibling projects.

**How does this PR change Premake's behavior?**

Specifying a linking decorator on a sibling project will result in it treating it as a sibling project not a system library.

**Anything else we should know?**

N/A

**Did you check all the boxes?**

- [x] Focus on a single fix or feature; remove any unrelated formatting or code changes
- [x] Add unit tests showing fix or feature works; all tests pass
- [x] Mention any [related issues](https://github.com/premake/premake-core/issues) (put `closes #XXXX` in comment to auto-close issue when PR is merged)
- [x] Follow our [coding conventions](https://github.com/premake/premake-core/blob/master/CONTRIBUTING.md#coding-conventions)
- [x] Minimize the number of commits
- [x] Align [documentation](https://github.com/premake/premake-core/tree/master/website) to your changes

*You can now [support Premake on our OpenCollective](https://opencollective.com/premake). Your contributions help us spend more time responding to requests like these!*

### CODE REVIEW

File: tests/config/test_links.lua [hunk 1]
```diff
@@ -222,3 +222,45 @@
...
+
+	function suite.canLink_StaticDecoratorSiblingLib()
+		links { "SiblingLibrary:static" }
+
+		project "SiblingLibrary"
+		kind "StaticLib"
+		language "C++"
+
+		local r = prepare("all", "fullpath")
+		test.isequal({ "bin/Debug/SiblingLibrary.lib" }, r)
```
Comment (nickclark2016) [inline tests/config/test_links.lua:254]: ".lib" feels hard coded to Windows file extension conventions.

Comment (nickclark2016) [inline tests/config/test_links.lua:254]: ".lib" feels hard coded to Windows file extension conventions.

Comment (samsinsane) [reply tests/config/test_links.lua:254]: Yeah, the whole file uses Windows as the target, I decided to keep with that since the logic applies to all platforms not just Linux.

Comment (nickclark2016) [reply tests/config/test_links.lua:254]: Sounds good.

**Review by nickclark2016 — APPROVED** [review]
